# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a84f424981f7e451ec97814b05cb334576ff1bc9c8270e8a50189089feda697f298f6b40ca60db000d122a60b1ca911322a6a5a3b6ea6158bb4d251f8d0a1bb9

test:
  secret_key_base: b8ffd314522ca23f6e72cbe79f91a49322d6b171590b7a6266ea3fd53a3385a17a389e68dc9eff45c1bb920f4837828605a26f86076ae2089849a790c7692191

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
